before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pw6xzNfaFkK7SxNTkR5qzmheMoBAGRcvBFpAuMdBZnFBlNV0M0OldqT4LSOWHqUJKwf/DzudwV6OHw/OKbBJxeod++Kzp+SI7I4bo99ijjXLBv1vQcHKm6JK0qPUTOoKv7Mkgozr9sHGV0rLbiSYsFHfF27OXho70k/7bibGk8a2u1YF/HnQ5qLoHtaTyQZoSiezU9oL7kVvIi/Md0+FZ8qWaGQ+WvhN9BDpQ9qH9JEi2boK/gx5NlX0M6o/Vhdndc9lAK2IKR++3XaGLedwacdPPd/iYpaJH9KYGTSXqqTaHPsQD4LoDR8ea3K8841CEDRekZyb8fBS7I8pme+9Er4AHey9tGzhX9VM9iyvA6dGiopiAWF2PyR9eOX8jJEJxnnnZjD5rlEHkUZ6bl8LEOQs8sff5m/phb37aGD/z8KfIMNIXRJOdv2QNz2Af8WbLQr+B/a0cPx+wTbJPhjGLrhqmNdf/vJpUtS0Q4DPTQLuaeWj2soAF6th07hZa1Kd1iFzhgLL4krCwUWKSgGf/u5ZcCq9xYKWYsiqlf7Z8lCUr7J8uHXy5XfQAEJW/1JX5tGUtMV49HvDfrjfkT2MgWYFl4MYCCcilVwpeplqRmTvIYs9Gt6Eak4/KJkZu1Mf7EnkE/FGOAiIWOLRDhaObQ49woZZUkexA/d5x2M3+Zc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
